/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Time = IDL.Int;
export const GoalCategory = IDL.Variant({
  'midTerm' : IDL.Null,
  'shortTerm' : IDL.Null,
  'longTerm' : IDL.Null,
});
export const InvestmentCategory = IDL.Variant({
  'fixedDeposits' : IDL.Null,
  'commodities' : IDL.Null,
  'realEstate' : IDL.Null,
  'equities' : IDL.Null,
  'bonds' : IDL.Null,
  'retirement' : IDL.Null,
});
export const InvestmentSubcategory = IDL.Variant({
  'fd' : IDL.Null,
  'etf' : IDL.Null,
  'nps' : IDL.Null,
  'stocks' : IDL.Null,
  'other' : IDL.Text,
  'gold' : IDL.Null,
  'mutualFund' : IDL.Null,
  'providentFund' : IDL.Null,
  'crypto' : IDL.Null,
  'governmentBond' : IDL.Null,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const GoalProgressSummary = IDL.Record({
  'progressPercentage' : IDL.Float64,
  'goalName' : IDL.Text,
  'goalId' : IDL.Nat,
  'targetAmount' : IDL.Float64,
  'targetDate' : Time,
  'category' : GoalCategory,
  'currentAmount' : IDL.Float64,
});
export const GoalCategoryBreakdown = IDL.Record({
  'midTermGoals' : IDL.Vec(GoalProgressSummary),
  'longTermGoals' : IDL.Vec(GoalProgressSummary),
  'shortTermGoals' : IDL.Vec(GoalProgressSummary),
});
export const GoalsAnalytics = IDL.Record({
  'categoryBreakdown' : GoalCategoryBreakdown,
  'totalAmountLinked' : IDL.Float64,
  'overallProgress' : IDL.Float64,
  'allGoals' : IDL.Vec(GoalProgressSummary),
  'totalGoalAmount' : IDL.Float64,
});
export const Investment = IDL.Record({
  'id' : IDL.Nat,
  'subcategory' : InvestmentSubcategory,
  'user' : IDL.Principal,
  'createdDate' : Time,
  'currentValue' : IDL.Float64,
  'category' : InvestmentCategory,
  'investedAmount' : IDL.Float64,
  'dateOfInvestment' : Time,
});
export const InvestmentSummary = IDL.Record({
  'pnlPercentage' : IDL.Float64,
  'totalInvested' : IDL.Float64,
  'currentPortfolioValue' : IDL.Float64,
  'gainLossAbsolute' : IDL.Float64,
});
export const InvestmentsAnalytics = IDL.Record({
  'allInvestments' : IDL.Vec(Investment),
  'summary' : InvestmentSummary,
});
export const FinancialDashboard = IDL.Record({
  'goalsAnalytics' : GoalsAnalytics,
  'investmentsAnalytics' : InvestmentsAnalytics,
});
export const FinancialGoal = IDL.Record({
  'id' : IDL.Nat,
  'name' : IDL.Text,
  'user' : IDL.Principal,
  'createdDate' : Time,
  'targetAmount' : IDL.Float64,
  'targetDate' : Time,
  'category' : GoalCategory,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addFinancialGoal' : IDL.Func(
      [IDL.Text, IDL.Float64, Time, GoalCategory],
      [IDL.Nat],
      [],
    ),
  'addInvestment' : IDL.Func(
      [
        InvestmentCategory,
        InvestmentSubcategory,
        IDL.Float64,
        IDL.Float64,
        Time,
      ],
      [IDL.Nat],
      [],
    ),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'deleteFinancialGoal' : IDL.Func([IDL.Nat], [], []),
  'deleteInvestment' : IDL.Func([IDL.Nat], [], []),
  'ensureInitialized' : IDL.Func([], [], []),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getDashboard' : IDL.Func([], [FinancialDashboard], []),
  'getFinancialGoal' : IDL.Func([IDL.Nat], [FinancialGoal], ['query']),
  'getGoalAnalytics' : IDL.Func([], [GoalsAnalytics], []),
  'getInvestment' : IDL.Func([IDL.Nat], [Investment], ['query']),
  'getInvestmentAnalytics' : IDL.Func([], [InvestmentsAnalytics], []),
  'getUserFinancialGoals' : IDL.Func([], [IDL.Vec(FinancialGoal)], ['query']),
  'getUserInvestments' : IDL.Func([], [IDL.Vec(Investment)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'linkInvestmentToGoal' : IDL.Func([IDL.Nat, IDL.Nat, IDL.Float64], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'unlinkInvestmentFromGoal' : IDL.Func([IDL.Nat, IDL.Nat], [], []),
  'updateFinancialGoal' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Float64, Time, GoalCategory],
      [],
      [],
    ),
  'updateInvestment' : IDL.Func(
      [
        IDL.Nat,
        InvestmentCategory,
        InvestmentSubcategory,
        IDL.Float64,
        IDL.Float64,
        Time,
      ],
      [],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Time = IDL.Int;
  const GoalCategory = IDL.Variant({
    'midTerm' : IDL.Null,
    'shortTerm' : IDL.Null,
    'longTerm' : IDL.Null,
  });
  const InvestmentCategory = IDL.Variant({
    'fixedDeposits' : IDL.Null,
    'commodities' : IDL.Null,
    'realEstate' : IDL.Null,
    'equities' : IDL.Null,
    'bonds' : IDL.Null,
    'retirement' : IDL.Null,
  });
  const InvestmentSubcategory = IDL.Variant({
    'fd' : IDL.Null,
    'etf' : IDL.Null,
    'nps' : IDL.Null,
    'stocks' : IDL.Null,
    'other' : IDL.Text,
    'gold' : IDL.Null,
    'mutualFund' : IDL.Null,
    'providentFund' : IDL.Null,
    'crypto' : IDL.Null,
    'governmentBond' : IDL.Null,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const GoalProgressSummary = IDL.Record({
    'progressPercentage' : IDL.Float64,
    'goalName' : IDL.Text,
    'goalId' : IDL.Nat,
    'targetAmount' : IDL.Float64,
    'targetDate' : Time,
    'category' : GoalCategory,
    'currentAmount' : IDL.Float64,
  });
  const GoalCategoryBreakdown = IDL.Record({
    'midTermGoals' : IDL.Vec(GoalProgressSummary),
    'longTermGoals' : IDL.Vec(GoalProgressSummary),
    'shortTermGoals' : IDL.Vec(GoalProgressSummary),
  });
  const GoalsAnalytics = IDL.Record({
    'categoryBreakdown' : GoalCategoryBreakdown,
    'totalAmountLinked' : IDL.Float64,
    'overallProgress' : IDL.Float64,
    'allGoals' : IDL.Vec(GoalProgressSummary),
    'totalGoalAmount' : IDL.Float64,
  });
  const Investment = IDL.Record({
    'id' : IDL.Nat,
    'subcategory' : InvestmentSubcategory,
    'user' : IDL.Principal,
    'createdDate' : Time,
    'currentValue' : IDL.Float64,
    'category' : InvestmentCategory,
    'investedAmount' : IDL.Float64,
    'dateOfInvestment' : Time,
  });
  const InvestmentSummary = IDL.Record({
    'pnlPercentage' : IDL.Float64,
    'totalInvested' : IDL.Float64,
    'currentPortfolioValue' : IDL.Float64,
    'gainLossAbsolute' : IDL.Float64,
  });
  const InvestmentsAnalytics = IDL.Record({
    'allInvestments' : IDL.Vec(Investment),
    'summary' : InvestmentSummary,
  });
  const FinancialDashboard = IDL.Record({
    'goalsAnalytics' : GoalsAnalytics,
    'investmentsAnalytics' : InvestmentsAnalytics,
  });
  const FinancialGoal = IDL.Record({
    'id' : IDL.Nat,
    'name' : IDL.Text,
    'user' : IDL.Principal,
    'createdDate' : Time,
    'targetAmount' : IDL.Float64,
    'targetDate' : Time,
    'category' : GoalCategory,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addFinancialGoal' : IDL.Func(
        [IDL.Text, IDL.Float64, Time, GoalCategory],
        [IDL.Nat],
        [],
      ),
    'addInvestment' : IDL.Func(
        [
          InvestmentCategory,
          InvestmentSubcategory,
          IDL.Float64,
          IDL.Float64,
          Time,
        ],
        [IDL.Nat],
        [],
      ),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'deleteFinancialGoal' : IDL.Func([IDL.Nat], [], []),
    'deleteInvestment' : IDL.Func([IDL.Nat], [], []),
    'ensureInitialized' : IDL.Func([], [], []),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getDashboard' : IDL.Func([], [FinancialDashboard], []),
    'getFinancialGoal' : IDL.Func([IDL.Nat], [FinancialGoal], ['query']),
    'getGoalAnalytics' : IDL.Func([], [GoalsAnalytics], []),
    'getInvestment' : IDL.Func([IDL.Nat], [Investment], ['query']),
    'getInvestmentAnalytics' : IDL.Func([], [InvestmentsAnalytics], []),
    'getUserFinancialGoals' : IDL.Func([], [IDL.Vec(FinancialGoal)], ['query']),
    'getUserInvestments' : IDL.Func([], [IDL.Vec(Investment)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'linkInvestmentToGoal' : IDL.Func([IDL.Nat, IDL.Nat, IDL.Float64], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'unlinkInvestmentFromGoal' : IDL.Func([IDL.Nat, IDL.Nat], [], []),
    'updateFinancialGoal' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Float64, Time, GoalCategory],
        [],
        [],
      ),
    'updateInvestment' : IDL.Func(
        [
          IDL.Nat,
          InvestmentCategory,
          InvestmentSubcategory,
          IDL.Float64,
          IDL.Float64,
          Time,
        ],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };