/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface FinancialDashboard {
  'goalsAnalytics' : GoalsAnalytics,
  'investmentsAnalytics' : InvestmentsAnalytics,
}
export interface FinancialGoal {
  'id' : bigint,
  'name' : string,
  'user' : Principal,
  'createdDate' : Time,
  'targetAmount' : number,
  'targetDate' : Time,
  'category' : GoalCategory,
}
export type GoalCategory = { 'midTerm' : null } |
  { 'shortTerm' : null } |
  { 'longTerm' : null };
export interface GoalCategoryBreakdown {
  'midTermGoals' : Array<GoalProgressSummary>,
  'longTermGoals' : Array<GoalProgressSummary>,
  'shortTermGoals' : Array<GoalProgressSummary>,
}
export interface GoalProgressSummary {
  'progressPercentage' : number,
  'goalName' : string,
  'goalId' : bigint,
  'targetAmount' : number,
  'targetDate' : Time,
  'category' : GoalCategory,
  'currentAmount' : number,
}
export interface GoalsAnalytics {
  'categoryBreakdown' : GoalCategoryBreakdown,
  'totalAmountLinked' : number,
  'overallProgress' : number,
  'allGoals' : Array<GoalProgressSummary>,
  'totalGoalAmount' : number,
}
export interface Investment {
  'id' : bigint,
  'subcategory' : InvestmentSubcategory,
  'user' : Principal,
  'createdDate' : Time,
  'currentValue' : number,
  'category' : InvestmentCategory,
  'investedAmount' : number,
  'dateOfInvestment' : Time,
}
export type InvestmentCategory = { 'fixedDeposits' : null } |
  { 'commodities' : null } |
  { 'realEstate' : null } |
  { 'equities' : null } |
  { 'bonds' : null } |
  { 'retirement' : null };
export type InvestmentSubcategory = { 'fd' : null } |
  { 'etf' : null } |
  { 'nps' : null } |
  { 'stocks' : null } |
  { 'other' : string } |
  { 'gold' : null } |
  { 'mutualFund' : null } |
  { 'providentFund' : null } |
  { 'crypto' : null } |
  { 'governmentBond' : null };
export interface InvestmentSummary {
  'pnlPercentage' : number,
  'totalInvested' : number,
  'currentPortfolioValue' : number,
  'gainLossAbsolute' : number,
}
export interface InvestmentsAnalytics {
  'allInvestments' : Array<Investment>,
  'summary' : InvestmentSummary,
}
export type Time = bigint;
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addFinancialGoal' : ActorMethod<
    [string, number, Time, GoalCategory],
    bigint
  >,
  'addInvestment' : ActorMethod<
    [InvestmentCategory, InvestmentSubcategory, number, number, Time],
    bigint
  >,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'deleteFinancialGoal' : ActorMethod<[bigint], undefined>,
  'deleteInvestment' : ActorMethod<[bigint], undefined>,
  'ensureInitialized' : ActorMethod<[], undefined>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getDashboard' : ActorMethod<[], FinancialDashboard>,
  'getFinancialGoal' : ActorMethod<[bigint], FinancialGoal>,
  'getGoalAnalytics' : ActorMethod<[], GoalsAnalytics>,
  'getInvestment' : ActorMethod<[bigint], Investment>,
  'getInvestmentAnalytics' : ActorMethod<[], InvestmentsAnalytics>,
  'getUserFinancialGoals' : ActorMethod<[], Array<FinancialGoal>>,
  'getUserInvestments' : ActorMethod<[], Array<Investment>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'linkInvestmentToGoal' : ActorMethod<[bigint, bigint, number], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'unlinkInvestmentFromGoal' : ActorMethod<[bigint, bigint], undefined>,
  'updateFinancialGoal' : ActorMethod<
    [bigint, string, number, Time, GoalCategory],
    undefined
  >,
  'updateInvestment' : ActorMethod<
    [bigint, InvestmentCategory, InvestmentSubcategory, number, number, Time],
    undefined
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];