/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export type Time = bigint;
export type InvestmentSubcategory = {
    __kind__: "fd";
    fd: null;
} | {
    __kind__: "etf";
    etf: null;
} | {
    __kind__: "nps";
    nps: null;
} | {
    __kind__: "stocks";
    stocks: null;
} | {
    __kind__: "other";
    other: string;
} | {
    __kind__: "gold";
    gold: null;
} | {
    __kind__: "mutualFund";
    mutualFund: null;
} | {
    __kind__: "providentFund";
    providentFund: null;
} | {
    __kind__: "crypto";
    crypto: null;
} | {
    __kind__: "governmentBond";
    governmentBond: null;
};
export interface Investment {
    id: bigint;
    subcategory: InvestmentSubcategory;
    user: Principal;
    createdDate: Time;
    currentValue: number;
    category: InvestmentCategory;
    investedAmount: number;
    dateOfInvestment: Time;
}
export interface FinancialDashboard {
    goalsAnalytics: GoalsAnalytics;
    investmentsAnalytics: InvestmentsAnalytics;
}
export interface InvestmentSummary {
    pnlPercentage: number;
    totalInvested: number;
    currentPortfolioValue: number;
    gainLossAbsolute: number;
}
export interface GoalCategoryBreakdown {
    midTermGoals: Array<GoalProgressSummary>;
    longTermGoals: Array<GoalProgressSummary>;
    shortTermGoals: Array<GoalProgressSummary>;
}
export interface GoalsAnalytics {
    categoryBreakdown: GoalCategoryBreakdown;
    totalAmountLinked: number;
    overallProgress: number;
    allGoals: Array<GoalProgressSummary>;
    totalGoalAmount: number;
}
export interface FinancialGoal {
    id: bigint;
    name: string;
    user: Principal;
    createdDate: Time;
    targetAmount: number;
    targetDate: Time;
    category: GoalCategory;
}
export interface GoalProgressSummary {
    progressPercentage: number;
    goalName: string;
    goalId: bigint;
    targetAmount: number;
    targetDate: Time;
    category: GoalCategory;
    currentAmount: number;
}
export interface UserProfile {
    name: string;
}
export interface InvestmentsAnalytics {
    allInvestments: Array<Investment>;
    summary: InvestmentSummary;
}
export enum GoalCategory {
    midTerm = "midTerm",
    shortTerm = "shortTerm",
    longTerm = "longTerm"
}
export enum InvestmentCategory {
    fixedDeposits = "fixedDeposits",
    commodities = "commodities",
    realEstate = "realEstate",
    equities = "equities",
    bonds = "bonds",
    retirement = "retirement"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    addFinancialGoal(name: string, targetAmount: number, targetDate: Time, category: GoalCategory): Promise<bigint>;
    addInvestment(category: InvestmentCategory, subcategory: InvestmentSubcategory, investedAmount: number, currentValue: number, dateOfInvestment: Time): Promise<bigint>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    deleteFinancialGoal(goalId: bigint): Promise<void>;
    deleteInvestment(investmentId: bigint): Promise<void>;
    ensureInitialized(): Promise<void>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getDashboard(): Promise<FinancialDashboard>;
    getFinancialGoal(goalId: bigint): Promise<FinancialGoal>;
    getGoalAnalytics(): Promise<GoalsAnalytics>;
    getInvestment(investmentId: bigint): Promise<Investment>;
    getInvestmentAnalytics(): Promise<InvestmentsAnalytics>;
    getUserFinancialGoals(): Promise<Array<FinancialGoal>>;
    getUserInvestments(): Promise<Array<Investment>>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    isCallerAdmin(): Promise<boolean>;
    linkInvestmentToGoal(goalId: bigint, investmentId: bigint, amountAllocated: number): Promise<void>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    unlinkInvestmentFromGoal(goalId: bigint, investmentId: bigint): Promise<void>;
    updateFinancialGoal(goalId: bigint, name: string, targetAmount: number, targetDate: Time, category: GoalCategory): Promise<void>;
    updateInvestment(investmentId: bigint, category: InvestmentCategory, subcategory: InvestmentSubcategory, investedAmount: number, currentValue: number, dateOfInvestment: Time): Promise<void>;
}
import type { FinancialDashboard as _FinancialDashboard, FinancialGoal as _FinancialGoal, GoalCategory as _GoalCategory, GoalCategoryBreakdown as _GoalCategoryBreakdown, GoalProgressSummary as _GoalProgressSummary, GoalsAnalytics as _GoalsAnalytics, Investment as _Investment, InvestmentCategory as _InvestmentCategory, InvestmentSubcategory as _InvestmentSubcategory, InvestmentSummary as _InvestmentSummary, InvestmentsAnalytics as _InvestmentsAnalytics, Time as _Time, UserProfile as _UserProfile, UserRole as _UserRole } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async addFinancialGoal(arg0: string, arg1: number, arg2: Time, arg3: GoalCategory): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.addFinancialGoal(arg0, arg1, arg2, to_candid_GoalCategory_n1(this._uploadFile, this._downloadFile, arg3));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addFinancialGoal(arg0, arg1, arg2, to_candid_GoalCategory_n1(this._uploadFile, this._downloadFile, arg3));
            return result;
        }
    }
    async addInvestment(arg0: InvestmentCategory, arg1: InvestmentSubcategory, arg2: number, arg3: number, arg4: Time): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.addInvestment(to_candid_InvestmentCategory_n3(this._uploadFile, this._downloadFile, arg0), to_candid_InvestmentSubcategory_n5(this._uploadFile, this._downloadFile, arg1), arg2, arg3, arg4);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addInvestment(to_candid_InvestmentCategory_n3(this._uploadFile, this._downloadFile, arg0), to_candid_InvestmentSubcategory_n5(this._uploadFile, this._downloadFile, arg1), arg2, arg3, arg4);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n7(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n7(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async deleteFinancialGoal(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteFinancialGoal(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteFinancialGoal(arg0);
            return result;
        }
    }
    async deleteInvestment(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteInvestment(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteInvestment(arg0);
            return result;
        }
    }
    async ensureInitialized(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.ensureInitialized();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.ensureInitialized();
            return result;
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n9(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n9(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n10(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n10(this._uploadFile, this._downloadFile, result);
        }
    }
    async getDashboard(): Promise<FinancialDashboard> {
        if (this.processError) {
            try {
                const result = await this.actor.getDashboard();
                return from_candid_FinancialDashboard_n12(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDashboard();
            return from_candid_FinancialDashboard_n12(this._uploadFile, this._downloadFile, result);
        }
    }
    async getFinancialGoal(arg0: bigint): Promise<FinancialGoal> {
        if (this.processError) {
            try {
                const result = await this.actor.getFinancialGoal(arg0);
                return from_candid_FinancialGoal_n32(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getFinancialGoal(arg0);
            return from_candid_FinancialGoal_n32(this._uploadFile, this._downloadFile, result);
        }
    }
    async getGoalAnalytics(): Promise<GoalsAnalytics> {
        if (this.processError) {
            try {
                const result = await this.actor.getGoalAnalytics();
                return from_candid_GoalsAnalytics_n14(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getGoalAnalytics();
            return from_candid_GoalsAnalytics_n14(this._uploadFile, this._downloadFile, result);
        }
    }
    async getInvestment(arg0: bigint): Promise<Investment> {
        if (this.processError) {
            try {
                const result = await this.actor.getInvestment(arg0);
                return from_candid_Investment_n26(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getInvestment(arg0);
            return from_candid_Investment_n26(this._uploadFile, this._downloadFile, result);
        }
    }
    async getInvestmentAnalytics(): Promise<InvestmentsAnalytics> {
        if (this.processError) {
            try {
                const result = await this.actor.getInvestmentAnalytics();
                return from_candid_InvestmentsAnalytics_n23(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getInvestmentAnalytics();
            return from_candid_InvestmentsAnalytics_n23(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserFinancialGoals(): Promise<Array<FinancialGoal>> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserFinancialGoals();
                return from_candid_vec_n34(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserFinancialGoals();
            return from_candid_vec_n34(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserInvestments(): Promise<Array<Investment>> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserInvestments();
                return from_candid_vec_n25(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserInvestments();
            return from_candid_vec_n25(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n9(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n9(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async linkInvestmentToGoal(arg0: bigint, arg1: bigint, arg2: number): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.linkInvestmentToGoal(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.linkInvestmentToGoal(arg0, arg1, arg2);
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(arg0);
            return result;
        }
    }
    async unlinkInvestmentFromGoal(arg0: bigint, arg1: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.unlinkInvestmentFromGoal(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.unlinkInvestmentFromGoal(arg0, arg1);
            return result;
        }
    }
    async updateFinancialGoal(arg0: bigint, arg1: string, arg2: number, arg3: Time, arg4: GoalCategory): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateFinancialGoal(arg0, arg1, arg2, arg3, to_candid_GoalCategory_n1(this._uploadFile, this._downloadFile, arg4));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateFinancialGoal(arg0, arg1, arg2, arg3, to_candid_GoalCategory_n1(this._uploadFile, this._downloadFile, arg4));
            return result;
        }
    }
    async updateInvestment(arg0: bigint, arg1: InvestmentCategory, arg2: InvestmentSubcategory, arg3: number, arg4: number, arg5: Time): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateInvestment(arg0, to_candid_InvestmentCategory_n3(this._uploadFile, this._downloadFile, arg1), to_candid_InvestmentSubcategory_n5(this._uploadFile, this._downloadFile, arg2), arg3, arg4, arg5);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateInvestment(arg0, to_candid_InvestmentCategory_n3(this._uploadFile, this._downloadFile, arg1), to_candid_InvestmentSubcategory_n5(this._uploadFile, this._downloadFile, arg2), arg3, arg4, arg5);
            return result;
        }
    }
}
function from_candid_FinancialDashboard_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _FinancialDashboard): FinancialDashboard {
    return from_candid_record_n13(_uploadFile, _downloadFile, value);
}
function from_candid_FinancialGoal_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _FinancialGoal): FinancialGoal {
    return from_candid_record_n33(_uploadFile, _downloadFile, value);
}
function from_candid_GoalCategoryBreakdown_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _GoalCategoryBreakdown): GoalCategoryBreakdown {
    return from_candid_record_n17(_uploadFile, _downloadFile, value);
}
function from_candid_GoalCategory_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _GoalCategory): GoalCategory {
    return from_candid_variant_n22(_uploadFile, _downloadFile, value);
}
function from_candid_GoalProgressSummary_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _GoalProgressSummary): GoalProgressSummary {
    return from_candid_record_n20(_uploadFile, _downloadFile, value);
}
function from_candid_GoalsAnalytics_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _GoalsAnalytics): GoalsAnalytics {
    return from_candid_record_n15(_uploadFile, _downloadFile, value);
}
function from_candid_InvestmentCategory_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _InvestmentCategory): InvestmentCategory {
    return from_candid_variant_n31(_uploadFile, _downloadFile, value);
}
function from_candid_InvestmentSubcategory_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _InvestmentSubcategory): InvestmentSubcategory {
    return from_candid_variant_n29(_uploadFile, _downloadFile, value);
}
function from_candid_Investment_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Investment): Investment {
    return from_candid_record_n27(_uploadFile, _downloadFile, value);
}
function from_candid_InvestmentsAnalytics_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _InvestmentsAnalytics): InvestmentsAnalytics {
    return from_candid_record_n24(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n11(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    goalsAnalytics: _GoalsAnalytics;
    investmentsAnalytics: _InvestmentsAnalytics;
}): {
    goalsAnalytics: GoalsAnalytics;
    investmentsAnalytics: InvestmentsAnalytics;
} {
    return {
        goalsAnalytics: from_candid_GoalsAnalytics_n14(_uploadFile, _downloadFile, value.goalsAnalytics),
        investmentsAnalytics: from_candid_InvestmentsAnalytics_n23(_uploadFile, _downloadFile, value.investmentsAnalytics)
    };
}
function from_candid_record_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    categoryBreakdown: _GoalCategoryBreakdown;
    totalAmountLinked: number;
    overallProgress: number;
    allGoals: Array<_GoalProgressSummary>;
    totalGoalAmount: number;
}): {
    categoryBreakdown: GoalCategoryBreakdown;
    totalAmountLinked: number;
    overallProgress: number;
    allGoals: Array<GoalProgressSummary>;
    totalGoalAmount: number;
} {
    return {
        categoryBreakdown: from_candid_GoalCategoryBreakdown_n16(_uploadFile, _downloadFile, value.categoryBreakdown),
        totalAmountLinked: value.totalAmountLinked,
        overallProgress: value.overallProgress,
        allGoals: from_candid_vec_n18(_uploadFile, _downloadFile, value.allGoals),
        totalGoalAmount: value.totalGoalAmount
    };
}
function from_candid_record_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    midTermGoals: Array<_GoalProgressSummary>;
    longTermGoals: Array<_GoalProgressSummary>;
    shortTermGoals: Array<_GoalProgressSummary>;
}): {
    midTermGoals: Array<GoalProgressSummary>;
    longTermGoals: Array<GoalProgressSummary>;
    shortTermGoals: Array<GoalProgressSummary>;
} {
    return {
        midTermGoals: from_candid_vec_n18(_uploadFile, _downloadFile, value.midTermGoals),
        longTermGoals: from_candid_vec_n18(_uploadFile, _downloadFile, value.longTermGoals),
        shortTermGoals: from_candid_vec_n18(_uploadFile, _downloadFile, value.shortTermGoals)
    };
}
function from_candid_record_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    progressPercentage: number;
    goalName: string;
    goalId: bigint;
    targetAmount: number;
    targetDate: _Time;
    category: _GoalCategory;
    currentAmount: number;
}): {
    progressPercentage: number;
    goalName: string;
    goalId: bigint;
    targetAmount: number;
    targetDate: Time;
    category: GoalCategory;
    currentAmount: number;
} {
    return {
        progressPercentage: value.progressPercentage,
        goalName: value.goalName,
        goalId: value.goalId,
        targetAmount: value.targetAmount,
        targetDate: value.targetDate,
        category: from_candid_GoalCategory_n21(_uploadFile, _downloadFile, value.category),
        currentAmount: value.currentAmount
    };
}
function from_candid_record_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    allInvestments: Array<_Investment>;
    summary: _InvestmentSummary;
}): {
    allInvestments: Array<Investment>;
    summary: InvestmentSummary;
} {
    return {
        allInvestments: from_candid_vec_n25(_uploadFile, _downloadFile, value.allInvestments),
        summary: value.summary
    };
}
function from_candid_record_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    subcategory: _InvestmentSubcategory;
    user: Principal;
    createdDate: _Time;
    currentValue: number;
    category: _InvestmentCategory;
    investedAmount: number;
    dateOfInvestment: _Time;
}): {
    id: bigint;
    subcategory: InvestmentSubcategory;
    user: Principal;
    createdDate: Time;
    currentValue: number;
    category: InvestmentCategory;
    investedAmount: number;
    dateOfInvestment: Time;
} {
    return {
        id: value.id,
        subcategory: from_candid_InvestmentSubcategory_n28(_uploadFile, _downloadFile, value.subcategory),
        user: value.user,
        createdDate: value.createdDate,
        currentValue: value.currentValue,
        category: from_candid_InvestmentCategory_n30(_uploadFile, _downloadFile, value.category),
        investedAmount: value.investedAmount,
        dateOfInvestment: value.dateOfInvestment
    };
}
function from_candid_record_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    name: string;
    user: Principal;
    createdDate: _Time;
    targetAmount: number;
    targetDate: _Time;
    category: _GoalCategory;
}): {
    id: bigint;
    name: string;
    user: Principal;
    createdDate: Time;
    targetAmount: number;
    targetDate: Time;
    category: GoalCategory;
} {
    return {
        id: value.id,
        name: value.name,
        user: value.user,
        createdDate: value.createdDate,
        targetAmount: value.targetAmount,
        targetDate: value.targetDate,
        category: from_candid_GoalCategory_n21(_uploadFile, _downloadFile, value.category)
    };
}
function from_candid_variant_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_variant_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    midTerm: null;
} | {
    shortTerm: null;
} | {
    longTerm: null;
}): GoalCategory {
    return "midTerm" in value ? GoalCategory.midTerm : "shortTerm" in value ? GoalCategory.shortTerm : "longTerm" in value ? GoalCategory.longTerm : value;
}
function from_candid_variant_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    fd: null;
} | {
    etf: null;
} | {
    nps: null;
} | {
    stocks: null;
} | {
    other: string;
} | {
    gold: null;
} | {
    mutualFund: null;
} | {
    providentFund: null;
} | {
    crypto: null;
} | {
    governmentBond: null;
}): {
    __kind__: "fd";
    fd: null;
} | {
    __kind__: "etf";
    etf: null;
} | {
    __kind__: "nps";
    nps: null;
} | {
    __kind__: "stocks";
    stocks: null;
} | {
    __kind__: "other";
    other: string;
} | {
    __kind__: "gold";
    gold: null;
} | {
    __kind__: "mutualFund";
    mutualFund: null;
} | {
    __kind__: "providentFund";
    providentFund: null;
} | {
    __kind__: "crypto";
    crypto: null;
} | {
    __kind__: "governmentBond";
    governmentBond: null;
} {
    return "fd" in value ? {
        __kind__: "fd",
        fd: value.fd
    } : "etf" in value ? {
        __kind__: "etf",
        etf: value.etf
    } : "nps" in value ? {
        __kind__: "nps",
        nps: value.nps
    } : "stocks" in value ? {
        __kind__: "stocks",
        stocks: value.stocks
    } : "other" in value ? {
        __kind__: "other",
        other: value.other
    } : "gold" in value ? {
        __kind__: "gold",
        gold: value.gold
    } : "mutualFund" in value ? {
        __kind__: "mutualFund",
        mutualFund: value.mutualFund
    } : "providentFund" in value ? {
        __kind__: "providentFund",
        providentFund: value.providentFund
    } : "crypto" in value ? {
        __kind__: "crypto",
        crypto: value.crypto
    } : "governmentBond" in value ? {
        __kind__: "governmentBond",
        governmentBond: value.governmentBond
    } : value;
}
function from_candid_variant_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    fixedDeposits: null;
} | {
    commodities: null;
} | {
    realEstate: null;
} | {
    equities: null;
} | {
    bonds: null;
} | {
    retirement: null;
}): InvestmentCategory {
    return "fixedDeposits" in value ? InvestmentCategory.fixedDeposits : "commodities" in value ? InvestmentCategory.commodities : "realEstate" in value ? InvestmentCategory.realEstate : "equities" in value ? InvestmentCategory.equities : "bonds" in value ? InvestmentCategory.bonds : "retirement" in value ? InvestmentCategory.retirement : value;
}
function from_candid_vec_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_GoalProgressSummary>): Array<GoalProgressSummary> {
    return value.map((x)=>from_candid_GoalProgressSummary_n19(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Investment>): Array<Investment> {
    return value.map((x)=>from_candid_Investment_n26(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_FinancialGoal>): Array<FinancialGoal> {
    return value.map((x)=>from_candid_FinancialGoal_n32(_uploadFile, _downloadFile, x));
}
function to_candid_GoalCategory_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: GoalCategory): _GoalCategory {
    return to_candid_variant_n2(_uploadFile, _downloadFile, value);
}
function to_candid_InvestmentCategory_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: InvestmentCategory): _InvestmentCategory {
    return to_candid_variant_n4(_uploadFile, _downloadFile, value);
}
function to_candid_InvestmentSubcategory_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: InvestmentSubcategory): _InvestmentSubcategory {
    return to_candid_variant_n6(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n8(_uploadFile, _downloadFile, value);
}
function to_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: GoalCategory): {
    midTerm: null;
} | {
    shortTerm: null;
} | {
    longTerm: null;
} {
    return value == GoalCategory.midTerm ? {
        midTerm: null
    } : value == GoalCategory.shortTerm ? {
        shortTerm: null
    } : value == GoalCategory.longTerm ? {
        longTerm: null
    } : value;
}
function to_candid_variant_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: InvestmentCategory): {
    fixedDeposits: null;
} | {
    commodities: null;
} | {
    realEstate: null;
} | {
    equities: null;
} | {
    bonds: null;
} | {
    retirement: null;
} {
    return value == InvestmentCategory.fixedDeposits ? {
        fixedDeposits: null
    } : value == InvestmentCategory.commodities ? {
        commodities: null
    } : value == InvestmentCategory.realEstate ? {
        realEstate: null
    } : value == InvestmentCategory.equities ? {
        equities: null
    } : value == InvestmentCategory.bonds ? {
        bonds: null
    } : value == InvestmentCategory.retirement ? {
        retirement: null
    } : value;
}
function to_candid_variant_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    __kind__: "fd";
    fd: null;
} | {
    __kind__: "etf";
    etf: null;
} | {
    __kind__: "nps";
    nps: null;
} | {
    __kind__: "stocks";
    stocks: null;
} | {
    __kind__: "other";
    other: string;
} | {
    __kind__: "gold";
    gold: null;
} | {
    __kind__: "mutualFund";
    mutualFund: null;
} | {
    __kind__: "providentFund";
    providentFund: null;
} | {
    __kind__: "crypto";
    crypto: null;
} | {
    __kind__: "governmentBond";
    governmentBond: null;
}): {
    fd: null;
} | {
    etf: null;
} | {
    nps: null;
} | {
    stocks: null;
} | {
    other: string;
} | {
    gold: null;
} | {
    mutualFund: null;
} | {
    providentFund: null;
} | {
    crypto: null;
} | {
    governmentBond: null;
} {
    return value.__kind__ === "fd" ? {
        fd: value.fd
    } : value.__kind__ === "etf" ? {
        etf: value.etf
    } : value.__kind__ === "nps" ? {
        nps: value.nps
    } : value.__kind__ === "stocks" ? {
        stocks: value.stocks
    } : value.__kind__ === "other" ? {
        other: value.other
    } : value.__kind__ === "gold" ? {
        gold: value.gold
    } : value.__kind__ === "mutualFund" ? {
        mutualFund: value.mutualFund
    } : value.__kind__ === "providentFund" ? {
        providentFund: value.providentFund
    } : value.__kind__ === "crypto" ? {
        crypto: value.crypto
    } : value.__kind__ === "governmentBond" ? {
        governmentBond: value.governmentBond
    } : value;
}
function to_candid_variant_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
